### ISSUE TITLE
TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by xinkaiwang** [yorkie/node-ifconfig-parser#2]
```
root@ubuntu-2gb-sfo1-01:~/src# node
> i = require('ifconfig');
[Function: getConfig]
> i(function(err,config){console.dir(config);});
undefined
> 
/root/src/node_modules/ifconfig/node_modules/ifconfig-parser/index.js:51
    ret.flags = flagsMh[1].split(',');
                       ^
TypeError: Cannot read property '1' of null
    at /root/src/node_modules/ifconfig/node_modules/ifconfig-parser/index.js:51:24
    at Array.map (native)
    at parse (/root/src/node_modules/ifconfig/node_modules/ifconfig-parser/index.js:42:17)
    at /root/src/node_modules/ifconfig/index.js:10:22
    at ChildProcess.exithandler (child_process.js:635:7)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:743:16)
    at Socket.<anonymous> (child_process.js:956:11)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)
```

BTW, I'm using Ubuntu 14.04.4 LTS

```
root@ubuntu-2gb-sfo1-01:~# ifconfig
eth0      Link encap:Ethernet  HWaddr 04:01:d3:db:fd:01  
          inet addr:107.170.222.198  Bcast:107.170.223.255  Mask:255.255.240.0
          inet6 addr: fe80::601:d3ff:fedb:fd01/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:18564 errors:0 dropped:0 overruns:0 frame:0
          TX packets:18318 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:6362180 (6.3 MB)  TX bytes:6668620 (6.6 MB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:35360 errors:0 dropped:0 overruns:0 frame:0
          TX packets:35360 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:6449566 (6.4 MB)  TX bytes:6449566 (6.4 MB)

root@ubuntu-2gb-sfo1-01:~# 
```

**Comment by PsyTae** [comment]
got the same error using raspian stretch

```
/node_code/script/node_modules/ifconfig-parser/index.js:51
    ret.flags = flagsMh[1].split(',');
                       ^

TypeError: Cannot read property '1' of null
    at /node_code/script/node_modules/ifconfig-parser/index.js:51:24
    at Array.map (<anonymous>)
    at Object.parse (/node_code/script/node_modules/ifconfig-parser/index.js:42:17)
    at child.execFile (/node_code/script/src/extras/networkSetup.js:27:43)
    at ChildProcess.exithandler (child_process.js:267:7)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
```

```
eth0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 192.168.0.1  netmask 255.255.255.0  broadcast 192.168.0.255
        ether b8:27:eb:12:21:55  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1  (Local Loopback)
        RX packets 426  bytes 38392 (37.4 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 426  bytes 38392 (37.4 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.254.1  netmask 255.255.255.0  broadcast 192.168.254.255
        inet6 fe80::ba27:ebff:fe47:7400  prefixlen 64  scopeid 0x20<link>
        ether b8:27:eb:47:74:00  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 221  bytes 17624 (17.2 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlan1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.249.27  netmask 255.255.0.0  broadcast 192.168.255.255
        inet6 fe80::7edd:90ff:fee5:f36e  prefixlen 64  scopeid 0x20<link>
        ether 7c:dd:90:e5:f3:6e  txqueuelen 1000  (Ethernet)
        RX packets 8091  bytes 1195820 (1.1 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 8565  bytes 2037433 (1.9 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```
